Repository bitzquad/docs-bitzquad-academy, pull requests merged in 2023-01, with the labels that each got.

#4 move dev env setup part form chap. 0 to new chap.
  docs/content/chapter_0.md
  docs/content/chapter_1.md
  docs/content/chapter_1_old.md
Labels: documentation

#6 Prerequisites Docs Update ✅
  docs/content/chapter_0.md
Labels: bug, documentation, enhancement

#10 Add next router docs
  docs/content/nextfeatures/next_router.md
Labels: documentation, enhancement

#8 fix images in dev env chapter. 🐛
  docs/content/chapter_1.md
  docs/img/chap_0/git_check.png
  docs/img/chap_0/node_check.png
  docs/img/chap_0/node_download.png
  docs/img/chap_0/vs_code_download.png
  docs/img/chap_0/vs_code_extensions_tab.png
  docs/img/chap_0/vs_code_install_tailwind.png
  docs/img/chap_0/vs_code_search_tailwind_extension.png
Labels: bug

#11 Add next link docs 📝
  docs/content/nextfeatures/next_link.md
Labels: documentation, enhancement

#12 Dev env doc update content 🐛
  docs/content/chapter_1.md
  docs/img/chap_1/git.png
  docs/img/chap_1/git_check.png
  docs/img/chap_1/node_check.png
  docs/img/chap_1/node_download.png
  docs/img/chap_1/vs_code_download.png
  docs/img/chap_1/vs_code_extensions_tab.png
  docs/img/chap_1/vs_code_init.png
  docs/img/chap_1/vs_code_install_tailwind.png
  docs/img/chap_1/vs_code_search_tailwind_extension.png
Labels: bug, documentation

#15 CAMP-8 About Docs
  docs/about.md
Labels: documentation

#16 CAMP-15 : Explain route types in NextJS 🍒
  docs/content/nextfeatures/routing_with_next.md
Labels: documentation, enhancement

#17 feat: add roadmap.png ✨
  docs/content/chapter_0.md
  docs/img/chap_0/roadmap.png
Labels: enhancement
